config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :products do
        resources :reviews
        resources :reviews do
          resources :users do
            resources :votes
          end
        end
      end
    end
  end

  devise_for :users
  resources :categories
  resources :products

  resources :emails, only: [:create]

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true

  HOST_MAP = {
    development: "http://localhost:3000",
    production: "https://cosmetrics.herokuapp.com"
  }

  def self.fetched_categories
    JSON.parse(Net::HTTP.get(URI.parse(HOST_MAP[Rails.env.to_sym] + "/api/v1/categories")))
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  def index
    render json: {
      makeup: makeup,
      beauty_supplements: beauty_supplements,
      bath_and_body: bath_and_body,
      hair: hair,
      fragrance: fragrance,
      tools: tools,
      nails: nails
    }
  end

  def makeup
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/5/department_tree")))
  end

  def beauty_supplements
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/4/department_tree")))
  end

  def bath_and_body
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/3/department_tree")))
  end

  def hair
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/6/department_tree")))
  end

  def fragrance
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/7/department_tree")))
  end

  def tools
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/352/department_tree")))
  end

  def nails
    JSON.parse(Net::HTTP.get(URI.parse("https://api.birchbox.com/products/v2/categories/913/department_tree")))
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id).order(:average_value)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: "Successfully added category."
    else
      render :new
    end
  end

  def edit
    @product = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      flash[:notice] = "Category was succesfully updated."
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    Category.destroy(params[:id])
    if !@category
      flash[:notice] = "Category succesfully deleted."
      redirect_to root_path
    else
      render :show
    end
  end

  protected
  def category_params
    params.require(:category).permit(:name, :description)
  end

  def authorize_user
    if !current_user.role == "admin"
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %>
<% end %>

app/views/categories/new.html.erb
<%= form_for(@category) do |f| %>

<% if @category.errors.any? %>
  <div id="error_explanation-categorys">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>

  <div class="row">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Category" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div id="all-category-products">
  <% if @products %>
    <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
        <div class="category-product">
          <%= image_tag("#{product.product_photo}", size: "150x150", class: "product") %><br>
          <%= link_to product.name, product_path(product) %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>