config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :products do
        resources :reviews
        resources :reviews do
          resources :users do
            resources :votes
          end
        end
      end
    end
  end

  devise_for :users
  resources :categories
  resources :products

  resources :emails, only: [:create]

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :users, through: :reviews

  max_paginates_per 10

  validates :average_value, presence: true
  validates :name, presence: true
  validates :brand, presence: true

  def average_rating
    sum = 0.0
    if reviews.length > 0
      reviews.each do |review|
        sum += review.rating.to_f
      end
      return (sum/reviews.length).round(1)
    end
  end

  def product_value(product)
    sum = 0.0
    if !product.reviews.empty?
      product.reviews.each do |review|
        sum += product_lifespan(review) / price_per_unit(product)
      end
      average_product_value = (sum / product.reviews.length).to_f
      return (average_product_value * average_rating).to_f
    end
  end

  def product_lifespan(review)
    usage_per_month = (review.times_used_per_week / 7.to_f) * 30.42
    months_product_lasts = review.months_product_lasts.to_f
    return usage_per_month * months_product_lasts
  end

  def price_per_unit(product)
    (product.price / product.size).to_f
  end

  def self.search(search)
    where("name ILIKE ? OR brand ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  def index
    render json: { products: ProductSerializer.products }
  end

  def show
    product = Product.find(params[:id])
    reviews = ProductSerializer.reviews(product)
    average_rating = product.average_rating
    product.average_value = product.product_value(product)
    render json: { product: product, rating: average_rating, reviews: reviews}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @all_categories = Category.fetched_categories
    @categories = Category.all
    if params[:search]
      @products = Product.search(params[:search]).page(params[:page]).per(10)
    else
      @products = Product.page(params[:page]).per(10)
    end
  end

  def show
    @product = Product.find(params[:id])
    if current_user
      @user_id = current_user.id
    else
      @user_id = ""
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "Successfully added product."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      flash[:notice] = "Product was succesfully updated."
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    if !@product
      flash[:notice] = "Product succesfully deleted."
      redirect_to products_path
    else
      render :show
    end
  end

  protected
  def product_params
    params.require(:product).permit(:name, :brand, :description, :price, :color, :product_photo, :category_id, :size)
  end

  def authorize_user
    if !current_user.role == "admin"
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

<% if @product.errors.any? %>
  <div id="error_explanation-products">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>

  <div class="row">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="row">
    <%= f.label :size, "Size (oz)" %>
    <%= f.text_field :size%>
  </div>

  <div class="row">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="row">
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "Please choose a category..." }) %>
  </div>

  <div class="row">
    <%= f.label :price, "Price ($)" %>
    <%= f.text_field :price%>
  </div>

  <div class="row">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="row">
    <%= f.label :product_photo, "Photo URL" %>
    <%= f.text_field :product_photo %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Product" %>
  </div>
<% end %>

app/views/products/_products.html.erb
<table>
  <% @products.each do |product| %>
      <tr>
      <td class="products">
        <%= link_to image_tag(product.product_photo, size: "150x150"), product_path(product) %><br>
        <%= link_to product.brand.upcase, product_path(product) %><br>
        <%= product.name %><br>
        <%= number_to_currency(product.price)%><br>
        <% if !current_user.nil? && current_user.role == "admin" %>
          <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_product_path(product) %> |
          <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/products/_reviews.html.erb
<h2>Reviews</h2>
<div id="reviews">
  <% @reviews.each do |review| %>
    <h3><%= image_tag(review.user.profile_photo, size: "30x30") %><%= " #{review.user.first_name} #{review.user.last_name} at #{review.updated_at}" %></h3>
    <p><%= review.body %></p>
    <% if !current_user.nil? %>
      <%= button_to "+1", review_upvote_path(review), class: "upvote", method: :post %>
      <%= button_to "-1", review_downvote_path(review), class: "downvote", method: :post %><br>
    <% end %>

    <% sum = 0 %>
    <% review.votes.each do |vote| %>
    <%  sum += vote.score %>
    <% end %>

    <% if sum != 0 %>
    <%= "Current Vote Score: #{sum}" %><br>
    <% end %>

    <% if !review.rating.nil? %>
      <%= "Rating: #{review.rating}" %><br>
    <% end %>

    <% if !current_user.nil? %>
      <% if current_user == review.user || current_user.is_admin? %>
        <%= link_to 'Edit', edit_product_review_path(@product, review) %> |
        <%= link_to 'Delete', product_review_path(@product, review), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
    <hr/>
  <% end %>
</div>

app/views/products/edit.html.erb
<%= render "form" %>

app/views/products/index.html.erb
<h1>Cosmetrics</h1>

<div class="row medium-unstack">
  <% @categories.each do |category| %>
    <div class="category columns"><%= link_to category.name, category_path(category) %></div>
  <% end %>
</div>

<% if @products.blank? %>
  <h4>There are no products containing the term <%= params[:search] %>.</h4>
<% end %>

<%= render "products" %>

<%= paginate @products %>

app/views/products/new.html.erb
<h2> Add New Makeup Product </h2>

<%= render 'form' %>

<h4><%= link_to "Back to All Products", products_path %></h4>

app/views/products/show.html.erb
<%= link_to "Back to All Products", products_path %>

<div id="react-app" data-product-id="<%= @product.id %>" data-current-user-id="<%= @user_id %>"></div>