config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :products do
        resources :reviews
        resources :reviews do
          resources :users do
            resources :votes
          end
        end
      end
    end
  end

  devise_for :users
  resources :categories
  resources :products

  resources :emails, only: [:create]

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

end

app/views/layouts/_admin_nav.html.erb
<li class="nav">Admin <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
  <ul class="menu vertical">
    <li><%= link_to "Add New Category", new_category_path %></li>
    <li><%= link_to "Add New Product", new_product_path %></li>
    <li><%= link_to "View All Users", admin_users_path %></li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<div id="engadget-footer-social-container">
  <footer id="engadget-footer-social">
    <div class="footer-left">
      <div class="newsletter">
        <h6>Sign up for our newsletter</h6>
        <form action="/emails" method="post">
          <div class="input-group">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input class="input-group-field" name="email" type="text" placeholder="Email address"/>
            <div class="input-group-button">
              <button type="submit"><i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i></button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="footer-right">
      <h6>Follow us</h6>
      <i class="fa fa-facebook-square fa-3x" aria-hidden="true"></i>
      <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
      <i class="fa fa-google-plus-square fa-3x" aria-hidden="true"></i>
      <i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i>
    </div>
  </footer>
</div>
<div id="engadget-footer-contact-details-container">
  <footer id="engadget-footer-contact-details">
    <div class="footer-left">
      <div class="contact-details">
        <ul>
          <li><i class="fa fa-phone fa-lg" aria-hidden="true"></i>508 648 7005</li>
          <li><a data-toggle="animatedModal10"><i class="fa fa-envelope-o" aria-hidden="true"></i> Contact us</a></li>
          <li><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i> Boston, MA</li>
        </ul>
      </div>
    </div>
    <div class="footer-right">
      <div class="logo">
        <i class="fa fa-copyright" aria-hidden="true"></i>
        <%= link_to "Cosmetrics", root_path %></div>
    </div>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu mobile-list" data-dropdown-menu data-close-on-click-inside="false">
      <li class="nav root-link"><%= link_to "Cosmetrics", root_path %></li>
      <li class="nav"><i class="fa fa-bars" aria-hidden="true"></i>
      <% if user_signed_in? %>
        <ul class="menu vertical">
          <li><%= link_to 'Edit Your Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, :method=>'delete' %></li>
          <% if current_user && current_user.role == "admin" %>
            <%= render 'layouts/admin_nav' %>
          <% end %>
        </ul>
        <% else %>
        <ul class="menu vertical">
          <li class="nav"><%= link_to 'Sign in', new_user_session_path %></li>
          <li class="nav"><%= link_to 'Register', new_user_registration_path %></li>
        </ul>
        <% end %>
      </li>
    </ul>
  </div>
  <%= render 'layouts/search_bar' %>
</div>

app/views/layouts/_search_bar.html.erb
<div class="top-bar-right">
  <ul class="menu">
    <li class="search-nav">
      <%= form_tag(products_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
      <button class="search-button"><i class="fa fa-search" aria-hidden="true"></i></button>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Cosmetrics" %></title>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class= "app">
      <%= yield %>
    </div>
    <div class="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>